<a href="https://colab.research.google.com/github/aryalkoshish/big_data/blob/main/Week_10_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part 1: Creating and Manipulating 2D Arrays**

In [1]:
import numpy as np

# Generate the 2D array with random integers between 1 and 100
dataset = np.random.randint(1, 101, size=(10, 10))

# Extract the first element (index 0, 0)
first_element = dataset[0, 0]

# Extract the last element (index 9, 9)
last_element = dataset[9, 9]

print("First Element:", first_element)
print("Last Element:", last_element)


First Element: 90
Last Element: 94


In [2]:
# Iterate over the 2D array
for row in dataset:
    for element in row:
        # Check if the element is divisible by both 2 and 3
        if element % 2 == 0 and element % 3 == 0:
            print(element)

90
72
78
72
42
6
18
18
12
6
54
84
78
84
66


In [6]:
# Reshape the original 2D array into a 1D array of length 100.
# Reshape the 2D array into a 1D array of length 100
reshaped_array = dataset.reshape(100)

print(reshaped_array)

[ 90  83  63  72  93  44  78  82  40  72  41  22  81   8  94  59  26  87
  27  49  86  92  70  42  21  85 100  44  63  76   6   3  17  92 100  13
  44  71  79  18  18  45  80  12  74  75   6  47  29   9  29  76  91  54
  79  25  43  45  23  61  25  52  63   2  84  41  67  14   9  14  56  31
  78   4  84  97  41  50  10  13  94  49  35  59  19  23  19  66  77  27
  34  29   3  91  99  55  76  51  40  94]


**Part 2: Performing Operations on Arrays**

In [9]:
# Convert the reshaped 1D array back to a 2D array of shape (10, 10)
original_shape_array = reshaped_array.reshape(10, 10)

# Element-wise sum of the two arrays
sum_result = original_shape_array + dataset

# Element-wise difference of the two arrays
diff_result = original_shape_array - dataset

# Element-wise product of the two arrays
prod_result = original_shape_array * dataset

print("Element-wise Sum:")
print(sum_result)
print()

print("Element-wise Difference:")
print(diff_result)
print()

print("Element-wise Product:")
print(prod_result)


Element-wise Sum:
[[180 166 126 144 186  88 156 164  80 144]
 [ 82  44 162  16 188 118  52 174  54  98]
 [172 184 140  84  42 170 200  88 126 152]
 [ 12   6  34 184 200  26  88 142 158  36]
 [ 36  90 160  24 148 150  12  94  58  18]
 [ 58 152 182 108 158  50  86  90  46 122]
 [ 50 104 126   4 168  82 134  28  18  28]
 [112  62 156   8 168 194  82 100  20  26]
 [188  98  70 118  38  46  38 132 154  54]
 [ 68  58   6 182 198 110 152 102  80 188]]

Element-wise Difference:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Element-wise Product:
[[ 8100  6889  3969  5184  8649  1936  6084  6724  1600  5184]
 [ 1681   484  6561    64  8836  3481   676  7569   729  2401]
 [ 7396  8464  4900  1764   441  7225 10000  1936  3969  5776]
 [   36     9   289  8464 10000   169  1936  5041  6241   324]
 [  324  2025  6400

In [10]:


# Calculate the mean, median, and standard deviation of the whole array
mean_value = np.mean(dataset)
median_value = np.median(dataset)
std_value = np.std(dataset)

# Calculate the minimum and maximum value of the whole array
min_value = np.min(dataset)
max_value = np.max(dataset)

# Calculate the 25th and 75th percentile of the whole array
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("Original 2D Array:")
print(dataset)
print()

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_value)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Original 2D Array:
[[ 90  83  63  72  93  44  78  82  40  72]
 [ 41  22  81   8  94  59  26  87  27  49]
 [ 86  92  70  42  21  85 100  44  63  76]
 [  6   3  17  92 100  13  44  71  79  18]
 [ 18  45  80  12  74  75   6  47  29   9]
 [ 29  76  91  54  79  25  43  45  23  61]
 [ 25  52  63   2  84  41  67  14   9  14]
 [ 56  31  78   4  84  97  41  50  10  13]
 [ 94  49  35  59  19  23  19  66  77  27]
 [ 34  29   3  91  99  55  76  51  40  94]]

Mean: 51.29
Median: 49.5
Standard Deviation: 29.381386965220006
Minimum Value: 2
Maximum Value: 100
25th Percentile: 25.0
75th Percentile: 78.0


In [11]:

# Find the sum along axis 0 (columns)
sum_along_axis_0 = np.sum(dataset, axis=0)

# Find the sum along axis 1 (rows)
sum_along_axis_1 = np.sum(dataset, axis=1)

print("Original 2D Array:")
print(dataset)
print()

print("Sum along Axis 0 (Columns):")
print(sum_along_axis_0)
print()

print("Sum along Axis 1 (Rows):")
print(sum_along_axis_1)


Original 2D Array:
[[ 90  83  63  72  93  44  78  82  40  72]
 [ 41  22  81   8  94  59  26  87  27  49]
 [ 86  92  70  42  21  85 100  44  63  76]
 [  6   3  17  92 100  13  44  71  79  18]
 [ 18  45  80  12  74  75   6  47  29   9]
 [ 29  76  91  54  79  25  43  45  23  61]
 [ 25  52  63   2  84  41  67  14   9  14]
 [ 56  31  78   4  84  97  41  50  10  13]
 [ 94  49  35  59  19  23  19  66  77  27]
 [ 34  29   3  91  99  55  76  51  40  94]]

Sum along Axis 0 (Columns):
[479 482 581 436 747 517 500 557 397 433]

Sum along Axis 1 (Rows):
[717 494 679 443 395 526 371 464 468 572]


**Part 3: Boolean Indexing, Masking and Broadcasting**

In [12]:


# Create a new boolean array where elements are True if the corresponding element in the original array is even, and False otherwise
even_mask = dataset % 2 == 0

print("Original 2D Array:")
print(dataset)
print()

print("Boolean Array - Even elements:")
print(even_mask)


Original 2D Array:
[[ 90  83  63  72  93  44  78  82  40  72]
 [ 41  22  81   8  94  59  26  87  27  49]
 [ 86  92  70  42  21  85 100  44  63  76]
 [  6   3  17  92 100  13  44  71  79  18]
 [ 18  45  80  12  74  75   6  47  29   9]
 [ 29  76  91  54  79  25  43  45  23  61]
 [ 25  52  63   2  84  41  67  14   9  14]
 [ 56  31  78   4  84  97  41  50  10  13]
 [ 94  49  35  59  19  23  19  66  77  27]
 [ 34  29   3  91  99  55  76  51  40  94]]

Boolean Array - Even elements:
[[ True False False  True False  True  True  True  True  True]
 [False  True False  True  True False  True False False False]
 [ True  True  True  True False False  True  True False  True]
 [ True False False  True  True False  True False False  True]
 [ True False  True  True  True False  True False False False]
 [False  True False  True False False False False False False]
 [False  True False  True  True False False  True False  True]
 [ True False  True  True  True False False  True  True False]
 [ True False 

In [13]:


# Mask the original array using the boolean array to get a new array containing only the even elements
even_elements_array = dataset[even_mask]

print("Original 2D Array:")
print(dataset)
print()

print("Boolean Array - Even elements:")
print(even_mask)
print()

print("New Array with Even Elements Only:")
print(even_elements_array)


Original 2D Array:
[[ 90  83  63  72  93  44  78  82  40  72]
 [ 41  22  81   8  94  59  26  87  27  49]
 [ 86  92  70  42  21  85 100  44  63  76]
 [  6   3  17  92 100  13  44  71  79  18]
 [ 18  45  80  12  74  75   6  47  29   9]
 [ 29  76  91  54  79  25  43  45  23  61]
 [ 25  52  63   2  84  41  67  14   9  14]
 [ 56  31  78   4  84  97  41  50  10  13]
 [ 94  49  35  59  19  23  19  66  77  27]
 [ 34  29   3  91  99  55  76  51  40  94]]

Boolean Array - Even elements:
[[ True False False  True False  True  True  True  True  True]
 [False  True False  True  True False  True False False False]
 [ True  True  True  True False False  True  True False  True]
 [ True False False  True  True False  True False False  True]
 [ True False  True  True  True False  True False False False]
 [False  True False  True False False False False False False]
 [False  True False  True  True False False  True False  True]
 [ True False  True  True  True False False  True  True False]
 [ True False 

In [15]:


# Generate a 1D array with random integers between 1 and 10
random_array = np.random.randint(1, 11, size=(10,))

# Add the 1D array to every row of the original 2D array using broadcasting
result_array = dataset + random_array[:, np.newaxis]

print("Original 2D Array:")
print(dataset)
print()

print("Random 1D Array:")
print(random_array)
print()

print("Result Array after Broadcasting:")
print(result_array)


Original 2D Array:
[[ 90  83  63  72  93  44  78  82  40  72]
 [ 41  22  81   8  94  59  26  87  27  49]
 [ 86  92  70  42  21  85 100  44  63  76]
 [  6   3  17  92 100  13  44  71  79  18]
 [ 18  45  80  12  74  75   6  47  29   9]
 [ 29  76  91  54  79  25  43  45  23  61]
 [ 25  52  63   2  84  41  67  14   9  14]
 [ 56  31  78   4  84  97  41  50  10  13]
 [ 94  49  35  59  19  23  19  66  77  27]
 [ 34  29   3  91  99  55  76  51  40  94]]

Random 1D Array:
[ 8  5  5  5 10 10  3  4  8  8]

Result Array after Broadcasting:
[[ 98  91  71  80 101  52  86  90  48  80]
 [ 46  27  86  13  99  64  31  92  32  54]
 [ 91  97  75  47  26  90 105  49  68  81]
 [ 11   8  22  97 105  18  49  76  84  23]
 [ 28  55  90  22  84  85  16  57  39  19]
 [ 39  86 101  64  89  35  53  55  33  71]
 [ 28  55  66   5  87  44  70  17  12  17]
 [ 60  35  82   8  88 101  45  54  14  17]
 [102  57  43  67  27  31  27  74  85  35]
 [ 42  37  11  99 107  63  84  59  48 102]]
